services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=Get from VPN provider
      - WIREGUARD_ADDRESSES=Get from VPN provider
      - SERVER_CITIES=Get from VPN provider
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /docker/qbittorrent:/config
      - /media/library/Downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
